spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 100MB
      # 重写了CommonsMultipartResolver,需要使用
      enabled: true
      max-request-size: 100MB
  #mongodb
  data:
    mongodb:
      host: localhost  #ip
      port: 27017   #端口
      database: elevator  #智慧电梯数据库名
      authentication-database: admin  #启动authentication鉴权的数据库
      username: root
      password: qiantao2114

  # kafka配置
  kafka:
    producer:
      bootstrap-servers: 10.10.200.21:9092
      topic: workflow_result
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      buffer-memory: 10485760
      batch-size: 2048
      retries: 1
    consumer:
      bootstrap-servers: 10.10.200.21:9092
      topic: workflow_result
      enable-auto-commit: false
      max-poll-records: 30
      group-id: test06   # ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    listener:
      concurrency: 5
      ack-mode: manual_immediate
      type: batch
      poll-timeout: 3000


  #mysql 数据源
  datasource:
    url: jdbc:mysql://${components.mysql.host}:${components.mysql.port}/xmarket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&autoReconnect=true
    username: ${components.mysql.user}
    password: ${components.mysql.pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver

  #rabbitmq
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: mq_host


  #redis
  redis:
    port: ${components.redis.port}
    host: ${components.redis.host}
    password: ${components.redis.pwd}
    database: 1
  #spring 任务配置
  task:
    scheduling:
      thread-name-prefix: scheduling-qt-
      pool:
        size: 2
      shutdown:
        await-termination: true #关闭线程
        await-termination-period: 30s #时间

    execution:
      thread-name-prefix: execution-qt-
      pool:
        core-size: 4 #核心线程数
        max-size: 5 #最大线程数
        allow-core-thread-timeout: true #当前线程数=coresize 线程是否会退出
        keep-alive: 60s #当前线程数>coresize 控制线程存活时间
  #返回页面的前缀和后缀
  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    cache: false

  #热部署配置
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: resources/**,static/**,templates/**
      #该目录下的内容修改不重启
      exclude: data/**

#########配置端口
server:
  port: 8808
  servlet:
    context-path: /sboot

#########配置日志
logging:
  level:
    com.qt.demo: info
  config: classpath:logback-spring.xml


####mybatis
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

components:
  redis:
    host: 127.0.0.1
    port: 6379
    pwd: qiantao2114
  mysql:
    host: 10.10.16.105
    port: 3306
    user: root
    pwd: Perfma888.

interceptor:
  excludePath:
    - /login
    - /user/*
    - /init/*
    - /swagger*/**
    - /v2/**
    - /webjars/**
  path:
    - /**
# es ip
elasticsearch:
  ip: 10.10.16.207  # ip，支持集群配置，每个ip之间用”,”隔开
  port: 9200  # 端口号
  http:
    connectTimeOut: 30000  # 连接超时时间
    socketTimeOut: 30000   # socket超时时间
    connectionRequestTimeOut: 30000  # 获取连接的超时时间
    maxConnectNum: 100    # 最大连接数
    maxConnectPerRoute: 100   # 最大路由连接数

showLog: false
execTask: false